=== LG-Online/LiGo/data/resources/dtd/LMML-CS.dtd
<!ELEMENT LMMLcode (listing?)>
<!ATTLIST LMMLcode
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT LMMLtext (#PCDATA | emphasized | option | poem | quoted | annotated | defined | formatted | math | code | LMMLcode | referencesLink | citesLink | externalLink)*>
<!ATTLIST LMMLtext
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT algorithm ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST algorithm
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT animation EMPTY>
<!ATTLIST animation
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT annotated (#PCDATA | LMMLtext)*>
<!ATTLIST annotated
	label ID #IMPLIED
>
<!ELEMENT bibItem (LMMLtext)>
<!ATTLIST bibItem
	bibKey ID #REQUIRED
>
<!ELEMENT bibliography (bibItem)*>
<!ATTLIST bibliography
	label ID #IMPLIED
	author CDATA #IMPLIED
	authorFirstName CDATA #IMPLIED
	bookYear CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT block (block | line)*>
<!ATTLIST block
	label ID #IMPLIED
>
<!ELEMENT citesLink EMPTY>
<!ATTLIST citesLink
	bibKey NMTOKEN #REQUIRED
	bib-module NMTOKEN #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT collection ((section | collection | glossary | bibliography | motivation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | formula)*)*>
<!ATTLIST collection
	strategy (beh | con) #IMPLIED
	type (course | exercise | coaching | example) #IMPLIED
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT conclusion ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST conclusion
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT defined (#PCDATA)>
<!ATTLIST defined
	label ID #IMPLIED
>
<!ELEMENT definition ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST definition
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT dummycmodel (#PCDATA)>
<!ELEMENT dummylist EMPTY>
<!ELEMENT dummytable EMPTY>
<!ELEMENT emphasized (#PCDATA)>
<!ATTLIST emphasized
	label ID #IMPLIED
>
<!ELEMENT example ((text | image | animation | sound | LMMLtext | table | olist | ulist | quotation | math | code | LMMLcode)*)*>
<!ATTLIST example
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT exercise (text | image | animation | sound | LMMLtext | table | olist | ulist | quotation | math | code | LMMLcode | (task, solution?))*>
<!ATTLIST exercise
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	type CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT externalLink (#PCDATA | emphasized | quoted | annotated | defined | formatted | math | code | LMMLcode)*>
<!ATTLIST externalLink
	uri CDATA #REQUIRED
	exturi CDATA #IMPLIED
	type (illustrates | exercises | defines | remark) #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT formatted (#PCDATA | formatted)*>
<!ATTLIST formatted
	label ID #IMPLIED
	style CDATA #REQUIRED
	title CDATA #IMPLIED
>
<!ELEMENT formula ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST formula
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT glossary (definition)*>
<!ATTLIST glossary
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT illustration ((text | image | poem | animation | sound | LMMLtext | table | olist | ulist | math | code | quotation | LMMLcode)*)*>
<!ATTLIST illustration
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT image EMPTY>
<!ATTLIST image
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT item (text | image | animation | sound | LMMLtext | table | olist | ulist)*>
<!ATTLIST item
	label ID #IMPLIED
>
<!ELEMENT line (#PCDATA | line)*>
<!ATTLIST line
	label ID #IMPLIED
>
<!ELEMENT listing (#PCDATA | block)*>
<!ATTLIST listing
	label ID #IMPLIED
>
<!ELEMENT lmml (section | collection | glossary | bibliography | motivation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | formula)>
<!ATTLIST lmml
	version CDATA #FIXED "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"
>
<!ELEMENT math (#PCDATA)>
<!ATTLIST math
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT motivation ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST motivation
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT olist (item)+>
<!ATTLIST olist
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT option (#PCDATA)*>
<!ATTLIST option
	label ID #IMPLIED
	target CDATA #IMPLIED
>
<!ELEMENT paragraph ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST paragraph
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT poem (poemlinegroup)*>
<!ATTLIST poem
	label ID #IMPLIED
	title CDATA #IMPLIED
	authorname CDATA #IMPLIED
	authorfamily CDATA #IMPLIED
	booktitle CDATA #IMPLIED
>
<!ELEMENT poemlinegroup (poemline)*>
<!ATTLIST poemlinegroup
	label ID #IMPLIED
>
<!ELEMENT poemline (#PCDATA | formatted)*>
<!ATTLIST poemline
	label ID #IMPLIED
>
<!ELEMENT proof ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST proof
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT proposition ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST proposition
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT quotation ((LMMLtext)*)*>
<!ATTLIST quotation
	label ID #IMPLIED
	title CDATA #IMPLIED
	authorname CDATA #IMPLIED
	authorfamily CDATA #IMPLIED
	booktitle CDATA #IMPLIED
	type (example | exercise | luecken) #IMPLIED
>
<!ELEMENT quoted (#PCDATA)>
<!ATTLIST quoted
	label ID #IMPLIED
	bib-module CDATA #IMPLIED
	bibKey NMTOKEN #IMPLIED
>
<!ELEMENT referencesLink (#PCDATA | emphasized | quoted | annotated | defined | formatted | math | code | LMMLcode | referencesLink)*>
<!ATTLIST referencesLink
	target NMTOKEN #REQUIRED
	target-module NMTOKEN #IMPLIED
	type (illustrates | exercises | defines | person | book | test ) #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT remark ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST remark
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
	audience (students | teachers) #IMPLIED
>
<!ELEMENT section ((section | poem | collection | glossary | bibliography | motivation | animation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | quotation | formula)*)*>
<!ATTLIST section
	strategy (beh | con) #IMPLIED
	type (course | exercise | coaching | example | oberbegriff| unterbegriff) #IMPLIED
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT solution ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST solution
	label ID #IMPLIED
	true (true | false) #IMPLIED
>
<!ELEMENT sound EMPTY>
<!ATTLIST sound
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT table (tableheading?, tablerow+)>
<!ATTLIST table
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT tabledata (text | image | animation | sound | LMMLtext | table | olist | ulist)*>
<!ELEMENT tableheading (tabledata+)>
<!ELEMENT tablerow (tabledata+)>
<!ELEMENT task ((text | image | animation | sound | externalLink | LMMLtext | table | olist | ulist | math | code | quotation | LMMLcode)*)*>
<!ATTLIST task
	type CDATA #IMPLIED
	target CDATA #IMPLIED
>
<!ELEMENT text EMPTY>
<!ATTLIST text
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT theorem ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST theorem
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT ulist (item)+>
<!ATTLIST ulist
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>

=== LG-Online/LiGo/xml_daten/sonstige/left.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/left.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../resources/dtd/LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN">
	<section label="frame" title="" author="Katrin Fischer">
		<section title="Wissensbereiche" author="Katrin Fischer" label="wissensbereiche" type="oberbegriff">
			<section label="prosa" title="Erzähltextanalyse" uri="prosa/erzaehltextanalyse.html"></section>
			<section label="lyrikanalyse" title="Lyrikanalyse" uri="lyrik/lyrikanalyse.html" type="unterbegriff"/>
			<section label="metrikanalyse" title="Metrik" author="Katrin Fischer" uri="metrik/metrikanalyse.html" type="unterbegriff"/>
			<section label="dramenanalyse" uri="drama/dramenanalyse.html" title="Dramenanalyse" type="unterbegriff"/>
			
			<section label="rhetorikanalyse" uri="rhetorik/rhetorikanalyse.html" title="Rhetorik/Stilistik" type="unterbegriff"/>
			<section label="editionsphilologie" uri="edition/editionsphilologie.html" title="Edition" type="unterbegriff"/>
			<section label="literaturtheorie" title="Literaturtheorie" uri="literaturtheorie/literaturtheorie.html" type="unterbegriff"/>
			
		<section label="fachgeschichtegermanistik" title="Fachgeschichte Germanistik" uri="fachgeschichtegerm/fachgeschichtegermanistik.html" type="unterbegriff"/>
			
		</section>
		<section label="verzeichnisse" title="Verzeichnisse" author="Katrin Fischer" type="oberbegriff">
			<section label="glossar" title="Glossar" author="Katrin Fischer" uri="glossar.html" type="unterbegriff"/>
			<section label="bibliographie" title="Bibliographie" author="Katrin Fischer" uri="bibliographie.html" type="unterbegriff"/>
			<section label="personen" title="Personen" author="Katrin Fischer" uri="personen.html" type="unterbegriff"/>
			<section type="unterbegriff" label="contents" title="Inhalt LiGo" uri="contents.html"/>
			<section type="unterbegriff" label="suchen" title="Suchen" uri="suchen.html"/>
			<section label="ueberligo" title="Über LiGo" author="Katrin Fischer" type="unterbegriff" uri="ueberligo.html">
		</section>
		</section>
		<section label="mitligolernen" author="Katrin Fischer" title="Mit LiGo lernen" type="oberbegriff">
			<section label="benutzung" title="Benutzung" author="Katrin Fischer" uri="benutzung.html" type="unterbegriff"/>
			<section label="forum" author="Katrin Fischer" title="Diskussionsforum" uri="http://www.li-go.de/forum" type="unterbegriff"/>
			<section label="test" title="Tests" author="Katrin Fischer" uri="test.html" type="unterbegriff"/>
			<!--section label="pdfForm" title="pdf/Drucken" author="Katrin Fischer" uri="selectForm.html" type="unterbegriff"/-->
		</section>
	</section>
</lmml>

=== LG-Online/LiGo/xml_daten/wissensbereiche/metrik/versfuss.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN">
	<section type="course" title="Versfuß" author="Sebastian Donat" creationTime="25.09.2007" label="versfuss" topics="Versfuß">
		<definition title="Versfuß" label="versfussdef">
			<LMMLtext>Aus der antiken Metrik stammende interne Gliederungseinheit des <referencesLink target="vers">
					<referencesLink show="new" type="defines" target="versdef">Verses</referencesLink>
				</referencesLink>, bestehend aus einer geregelten Abfolge von Hebungenund Senkungen</LMMLtext>
		</definition>
		<illustration>
			<LMMLtext>In der deutschen Versifikation werden meist nur zwei  und dreisilbige Verfüße verwendet. Im einzelnen sind dies:</LMMLtext>
			<ulist>
				<item>
					<LMMLtext>zweisilbig: <referencesLink target="jambus">
							<referencesLink show="new" type="defines" target="jambusdef">Jambus</referencesLink>
						</referencesLink>, <referencesLink target="trochaeus">
							<referencesLink show="new" type="defines" target="trochaeusdef">Trochäus</referencesLink>
						</referencesLink>; beim ebenfalls zweisilbigen <referencesLink target="spondeus">
							<referencesLink show="new" type="defines" target="spondeusdef">Spondeus</referencesLink>
						</referencesLink> handelt es sich eher um eine rhythmische Variante ‚echter’ Versfüße</LMMLtext>
				</item>
				<item>
					<LMMLtext>dreisilbig: <referencesLink target="daktylus">
							<referencesLink show="new" type="defines" target="daktylusdef">Daktylus</referencesLink>
						</referencesLink>, <referencesLink target="amphibrachys">
							<referencesLink show="new" type="defines" target="amphibrachysdef">Amphibrachys</referencesLink>
						</referencesLink> und <referencesLink target="anapaest">
							<referencesLink show="new" type="defines" target="anapaestdef">Anapäst</referencesLink>
						</referencesLink>.</LMMLtext>
				</item>
			</ulist>
			<LMMLtext>Es gibt zahlreiche Versuche, den einzelnen Versfüßen aufgrund ihrer jeweiligen rhythmischen Struktur eine Semantik bzw. einen spezifischen Ausdruckscharakter zuzuweisen. Hier ist jedoch Vorsicht geboten, da eine solche interne bzw. ikonische Relation zwischen Metrum und Semantik, sofern sie überhaupt sinnvoll bestimmbar ist, immer nur potentieller Natur sein kann und sich ggf. erst im Bezug zum konkreten Gedichtgegenstand entfaltet.</LMMLtext>
		</illustration>
	</section>
</lmml>

=== LG-Online/LiGo/data/xml_wissensbereiche/rhetorik/docere.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"><section type="course" title="docere" author="Uwe Spörl" creationTime="08.04.2007" label="docere" topics="docere"><illustration><LMMLtext>lat.: unterrichten, belehren, informieren</LMMLtext></illustration><definition title="docere" label="doceredef"><LMMLtext>Wirkungsprinzip der <referencesLink show="new" type="defines" target="persuasiodef"><referencesLink target="persuasio">persuasio</referencesLink></referencesLink>: Beeinflussung durch Information und Argumentation</LMMLtext></definition><illustration><LMMLtext>Um ein Publikum zu überzeugen, kann sich ein Autor oder Redner auf die jeweilige Sachlage verlassen, die er möglichst nüchtern, klar und präzise aufbereitet und darstellt. Die Sache soll gleichsam ‚für sich selbst sprechen’ – oder zumindest diesen Eindruck erwecken. Denn natürlich ist auch der sachlich informierende Redner parteiisch (etwa bei der Auswahl der Aspekte der jeweiligen Sache); aber er hat Argumente für seine Position und ist daher in der Lage auf Affekterregung (<referencesLink show="new" type="defines" target="moveredef"><referencesLink target="movere">movere</referencesLink></referencesLink>) und entsprechenden <referencesLink target="elocutiomitornatus">ornatus</referencesLink>  zu verzichten.</LMMLtext></illustration></section></lmml>

=== LG-Online/LiGo/data/xml_wissensbereiche/metrik/senkung.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"><section type="course" title="Senkung" author="Sebastian Donat" creationTime="24.03.2008" label="senkung" topics="Senkung"><definition title="Senkung" label="senkungdef"><LMMLtext>Durch das <referencesLink target="metrischesschema"><referencesLink show="new" type="defines" target="metrischesschemadef">metrische Schema</referencesLink></referencesLink> nach Anzahl und/oder Position festgelegte nicht-prominente Silbe im Vers (<referencesLink target="silbenprominenz"><referencesLink show="new" type="defines" target="silbenprominenzdef">Silbenprominenz</referencesLink></referencesLink>). – Senkungen können im konkreten Verstext und im Vortrag ‚realisiert’, d.h. sprachlich umgesetzt werden, dies ist aber keinesfalls zwingend (<referencesLink target="rhythmusdeskonkreteneinzelverses"><referencesLink show="new" type="defines" target="rhythmusdeskonkreteneinzelversesdef">Rhythmus des konkreten Einzelverses</referencesLink></referencesLink>; <referencesLink target="einzelvortrag"><referencesLink show="new" type="defines" target="einzelvortragdef">Einzelvortrag</referencesLink></referencesLink>).</LMMLtext></definition><illustration><LMMLtext><referencesLink type="illustrates" target="beispielsenkungBsp"></referencesLink></LMMLtext></illustration><section type="example" title="Beispiel Senkung" label="beispielsenkungBsp">  <illustration label="beispielsenkungBspIllu"><LMMLtext>Im (aus der englischen Dichtung übernommenen) deutschen Blankvers sind je nach <referencesLink target="kadenzversausgang"><referencesLink show="new" type="defines" target="kadenzversausgangdef">Kadenz</referencesLink></referencesLink> fünf bis sechs Senkungen vorgesehen, und zwar an der 1., 3., 5., 7., 9. und ggf. 11. Position im Vers.</LMMLtext></illustration></section></section></lmml>

=== LG-Online/LiGo/xml_daten/wissensbereiche/fachgeschichtegerm/fachgeschichtegermanistik.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/left.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd/LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN">
	<section type="coaching" title="Fachgeschichte Germanistik" author="Katrin Fischer" creationTime="02.05.2006" label="fachgeschichtegermanistik">
		<illustration>
			<table style="invisible">
				<tablerow>
					<tabledata>
						<LMMLtext/>
						<LMMLtext>In diesem Bereich werden die Grundzüge der Fachegschichte der Germanistik erläutert. [Im Aufbau]</LMMLtext>
						<LMMLtext type="inhaltsverzeichnis" uri="geschichtederliteraturwissenschaft"/>
					</tabledata>
				</tablerow>
			</table>
		</illustration>
	</section>
</lmml>
