=== LG-Online/LiGo/data/resources/dtd/LMML-CS.dtd
<!ELEMENT LMMLcode (listing?)>
<!ATTLIST LMMLcode
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT LMMLtext (#PCDATA | emphasized | option | poem | quoted | annotated | defined | formatted | math | code | LMMLcode | referencesLink | citesLink | externalLink)*>
<!ATTLIST LMMLtext
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT algorithm ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST algorithm
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT animation EMPTY>
<!ATTLIST animation
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT annotated (#PCDATA | LMMLtext)*>
<!ATTLIST annotated
	label ID #IMPLIED
>
<!ELEMENT bibItem (LMMLtext)>
<!ATTLIST bibItem
	bibKey ID #REQUIRED
>
<!ELEMENT bibliography (bibItem)*>
<!ATTLIST bibliography
	label ID #IMPLIED
	author CDATA #IMPLIED
	authorFirstName CDATA #IMPLIED
	bookYear CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT block (block | line)*>
<!ATTLIST block
	label ID #IMPLIED
>
<!ELEMENT citesLink EMPTY>
<!ATTLIST citesLink
	bibKey NMTOKEN #REQUIRED
	bib-module NMTOKEN #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT collection ((section | collection | glossary | bibliography | motivation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | formula)*)*>
<!ATTLIST collection
	strategy (beh | con) #IMPLIED
	type (course | exercise | coaching | example) #IMPLIED
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT conclusion ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST conclusion
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT defined (#PCDATA)>
<!ATTLIST defined
	label ID #IMPLIED
>
<!ELEMENT definition ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST definition
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT dummycmodel (#PCDATA)>
<!ELEMENT dummylist EMPTY>
<!ELEMENT dummytable EMPTY>
<!ELEMENT emphasized (#PCDATA)>
<!ATTLIST emphasized
	label ID #IMPLIED
>
<!ELEMENT example ((text | image | animation | sound | LMMLtext | table | olist | ulist | quotation | math | code | LMMLcode)*)*>
<!ATTLIST example
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT exercise (text | image | animation | sound | LMMLtext | table | olist | ulist | quotation | math | code | LMMLcode | (task, solution?))*>
<!ATTLIST exercise
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	type CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT externalLink (#PCDATA | emphasized | quoted | annotated | defined | formatted | math | code | LMMLcode)*>
<!ATTLIST externalLink
	uri CDATA #REQUIRED
	exturi CDATA #IMPLIED
	type (illustrates | exercises | defines | remark) #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT formatted (#PCDATA | formatted)*>
<!ATTLIST formatted
	label ID #IMPLIED
	style CDATA #REQUIRED
	title CDATA #IMPLIED
>
<!ELEMENT formula ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST formula
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT glossary (definition)*>
<!ATTLIST glossary
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT illustration ((text | image | poem | animation | sound | LMMLtext | table | olist | ulist | math | code | quotation | LMMLcode)*)*>
<!ATTLIST illustration
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT image EMPTY>
<!ATTLIST image
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT item (text | image | animation | sound | LMMLtext | table | olist | ulist)*>
<!ATTLIST item
	label ID #IMPLIED
>
<!ELEMENT line (#PCDATA | line)*>
<!ATTLIST line
	label ID #IMPLIED
>
<!ELEMENT listing (#PCDATA | block)*>
<!ATTLIST listing
	label ID #IMPLIED
>
<!ELEMENT lmml (section | collection | glossary | bibliography | motivation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | formula)>
<!ATTLIST lmml
	version CDATA #FIXED "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"
>
<!ELEMENT math (#PCDATA)>
<!ATTLIST math
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT motivation ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST motivation
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT olist (item)+>
<!ATTLIST olist
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT option (#PCDATA)*>
<!ATTLIST option
	label ID #IMPLIED
	target CDATA #IMPLIED
>
<!ELEMENT paragraph ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST paragraph
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT poem (poemlinegroup)*>
<!ATTLIST poem
	label ID #IMPLIED
	title CDATA #IMPLIED
	authorname CDATA #IMPLIED
	authorfamily CDATA #IMPLIED
	booktitle CDATA #IMPLIED
>
<!ELEMENT poemlinegroup (poemline)*>
<!ATTLIST poemlinegroup
	label ID #IMPLIED
>
<!ELEMENT poemline (#PCDATA | formatted)*>
<!ATTLIST poemline
	label ID #IMPLIED
>
<!ELEMENT proof ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST proof
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT proposition ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST proposition
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT quotation ((LMMLtext)*)*>
<!ATTLIST quotation
	label ID #IMPLIED
	title CDATA #IMPLIED
	authorname CDATA #IMPLIED
	authorfamily CDATA #IMPLIED
	booktitle CDATA #IMPLIED
	type (example | exercise | luecken) #IMPLIED
>
<!ELEMENT quoted (#PCDATA)>
<!ATTLIST quoted
	label ID #IMPLIED
	bib-module CDATA #IMPLIED
	bibKey NMTOKEN #IMPLIED
>
<!ELEMENT referencesLink (#PCDATA | emphasized | quoted | annotated | defined | formatted | math | code | LMMLcode | referencesLink)*>
<!ATTLIST referencesLink
	target NMTOKEN #REQUIRED
	target-module NMTOKEN #IMPLIED
	type (illustrates | exercises | defines | person | book | test ) #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT remark ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST remark
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
	audience (students | teachers) #IMPLIED
>
<!ELEMENT section ((section | poem | collection | glossary | bibliography | motivation | animation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | quotation | formula)*)*>
<!ATTLIST section
	strategy (beh | con) #IMPLIED
	type (course | exercise | coaching | example | oberbegriff| unterbegriff) #IMPLIED
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT solution ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST solution
	label ID #IMPLIED
	true (true | false) #IMPLIED
>
<!ELEMENT sound EMPTY>
<!ATTLIST sound
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT table (tableheading?, tablerow+)>
<!ATTLIST table
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT tabledata (text | image | animation | sound | LMMLtext | table | olist | ulist)*>
<!ELEMENT tableheading (tabledata+)>
<!ELEMENT tablerow (tabledata+)>
<!ELEMENT task ((text | image | animation | sound | externalLink | LMMLtext | table | olist | ulist | math | code | quotation | LMMLcode)*)*>
<!ATTLIST task
	type CDATA #IMPLIED
	target CDATA #IMPLIED
>
<!ELEMENT text EMPTY>
<!ATTLIST text
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT theorem ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST theorem
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT ulist (item)+>
<!ATTLIST ulist
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>

=== LG-Online/LiGo/xml_daten/wissensbereiche/drama/theateraufdemtheater1.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"><section type="course" title="Theater auf dem Theater" author="Martin Huber, Elisabeth Böhm" creationTime="19.04.2007" label="theateraufdemtheater1" topics="Theater auf dem Theater"><definition title="Theater auf dem Theater" label="theateraufdemtheater1def"><LMMLtext>In der Dramenhandlung verankertes Schauspiel auf der Bühne, das für diese deutende, kommentierende oder selbstreferentielle Funktion übernehmen kann.</LMMLtext></definition><illustration><LMMLtext>Das Theater auf dem Theater, also eine auf der eigentlichen Bühne dargestellte dramatische Handlung, verdoppelt die dramatische Kommunikationsstruktur, indem es diese auf der Bühne reproduziert und so Darsteller wiederum zu Darstellern und Zuschauern macht. Es macht innerhalb der primären eine zweite Fiktionsebene auf. Damit kann die primäre Dramenhandlung kommentiert, auf diese eingewirkt, oder sie in illusionsbrechender Weise als Inszenierung entlarvt werden.</LMMLtext><LMMLtext>Von den Dramen Shakespeares (<formatted style="buchtitel">Hamlet</formatted>, <formatted style="buchtitel">Ein Sommernachtstraum</formatted>) übernahmen die Romantiker (Tieck: <formatted style="buchtitel">Der gestiefelte Kater</formatted>) diese Möglichkeit, im Stück selbstreferentiell auf das dramatische Kommunikationsmodell zu verweisen. Die zusätzliche Fiktionsebene verweist zunächst auf das eigentliche Stück als Fiktion, dann aber auch auf die Möglichkeiten der Wirkung von ‚Theater’ auf ‚Realität’.</LMMLtext><LMMLtext><referencesLink type="illustrates" target="beispieltheateraufdemtheaterBsp"></referencesLink></LMMLtext></illustration><section type="example" title="Beispiel Theater auf dem Theater" label="beispieltheateraufdemtheaterBsp"><quotation booktitle="Hamlet" authorname="William" authorfamily="Shakespeare"><LMMLtext type="br"><formatted style="regie">Die Trompeten ertönen; es folgt die Pantomime</formatted></LMMLtext><LMMLtext type="br"><formatted style="regie">Ein König und eine Königin treten voller Liebesbezeugungen ein, die Königin umarmt ihn und er sie. Sie kniet sich hin und richtet an ihn Gesten heftiger Beteuerung, er hebt sie auf und lehnt seinen Kopf auf ihren Nacken. Er legt sich nieder auf einen Blumenhügel; sie sieht, dass er schläft, und verläßt ihn. Bald kommt ein anderer Mann, nimmt ihm die Krone ab und küßt sie, gießt Gift in die Ohren des schlafenden und verläßt ihn. Die Königin kehrt zurück, findet den König tot vor und gibt Anzeichen leidenschaftlicher Trauer; der Giftmörder kommt mit drei oder vier Statisten wieder herein und scheint ihren Schmerz zu teilen; der Leichnam wird weggetragen. Der Giftmörder wirbt um die Königin mit Geschenken; für eine Weile scheint sie abweisend, nimmt aber am Ende seine Liebe an.
Beide gehen ab.
</formatted></LMMLtext><LMMLtext type="br">OPHELIA: Was bedeutet dies, mein Prinz?</LMMLtext><LMMLtext type="br">HAMLET: Je nun, dies ist schleichende Schurkerei, es bedeutet Böses.</LMMLtext></quotation><illustration label="beispieltheateraufdemtheaterBspIllu"><LMMLtext>Auf der Handlungsebene sind Schauspieler ins Schloß gekommen. In der Pantomime vor dem eigentlich gezeigten Schauspiel, das allerdings unterbrochen wird, kündigen die Schauspieler dem dänischen Hof die Dramenhandlung an, die dem entspricht, was Hamlet vom Geist über den Tod seines Vaters gehört hat.</LMMLtext></illustration></section></section></lmml>

=== LG-Online/LiGo/xml_daten/wissensbereiche/rhetorik/antithesemitoxymoronundparadoxon.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN">
	<section type="course" title="Antithese (mit Oxymoron und Paradoxon)" author="Uwe Spörl"
		creationTime="08.04.2007" label="antithesemitoxymoronundparadoxon" topics="Antithese">
		<illustration>
			<LMMLtext>griech.: <formatted style="hervorhebung">antithesis</formatted>: Gegensatz –
				griech.: <formatted style="hervorhebung">oxymoron</formatted>: scharfer Unsinn –
				griech.: <formatted style="hervorhebung">paradoxon</formatted>: wider den
				Anschein</LMMLtext>
		</illustration>
		<definition title="Antithese"
			label="antithesemitoxymoronundparadoxondef">
			<LMMLtext>Gedankenfigur: Gegenüberstellung zweier sich (semantisch)
				widersprechender Ausdrücke</LMMLtext>
		</definition>
		<illustration>
			<LMMLtext>In der Antithese wird ein Gegensatz durch entsprechende Ausdrücke (Wörter,
				Wortgruppen, Teilsätze, Sätze) besonders deutlich herausgearbeitet. Dies geschieht
				entweder alleine durch die jeweiligen Ausdrücke bzw. die von diesen bezeichneten
				Gegenstände, Sachverhalte oder Gedanken, häufig werden diese aber so angeordnet,
				dass der Gegensatz besonders deutlich wird, etwa durch zusätzliche Verwendung der
				Wortfiguren <referencesLink target="parallelismus"><referencesLink show="new"
						type="defines" target="parallelismusdef"
					>Parallelismus</referencesLink></referencesLink> oder <referencesLink
					target="chiasmus"><referencesLink show="new" type="defines" target="chiasmusdef"
						>Chiasmus</referencesLink></referencesLink>.</LMMLtext>
			<LMMLtext>Das Oxymoron kann als besondere Form der Antithese gelten, in der die
				antithetischen Ausdrücke einander weniger gegenübergestellt werden als vielmehr
				direkt miteinander verknüpft werden: Es werden also zwei Ausdrücke, die sich
				(inhaltlich) ausschließen, zu einem komplexen Ausdruck zusammengeführt, der dem
				Adressaten der Äußerung zu denken gibt, weil dieser natürlich versucht, dem
				(scheinbar) sinnlosen Oxymoron doch einen Sinn abzugewinnen. Das Oxymoron kann also
				als Unsinn abgetan werden, zum Nachdenken anregen oder aber auch zum Lachen bringen.
				In jedem Fall aber wirkt es paradox, weil es so deutlich von dem abweicht, was man
				für gewöhnlich zu hören und zu lesen bekommt.</LMMLtext>
			<LMMLtext>Dieser Effekt der Paradoxie kann freilich nicht nur von Oxymora ausgelöst
				werden; er tritt vielmehr immer dann auf, wenn etwas bewusst gegen den Anschein oder
				die übliche Auffassung gerichtet ist, man aber (warum auch immer) geneigt ist, es
				gerade nicht als Unsinn abzutun.</LMMLtext>
			<LMMLtext><referencesLink type="illustrates"
					target="beispielantithesemitoxymoronundparadoxonBsp"/></LMMLtext>
		</illustration>
		<section type="example" title="Beispiel Antithese (mit Oxymoron und Paradoxon)"
			label="beispielantithesemitoxymoronundparadoxonBsp">
			<illustration label="beispielantithesemitoxymoronundparadoxonBspIllu">
				<LMMLtext>Antithesen werden häufig durch die rhetorischen Wortfiguren des
						<referencesLink show="new" type="defines" target="parallelismusdef"
						>Parallelismus</referencesLink> oder <referencesLink show="new"
						type="defines" target="chiasmusdef">Chiasmus</referencesLink> unterstützt.</LMMLtext>
				<LMMLtext>Oxymora, die offensichtlich (schon wegen ihrer Autoren etwa) darauf
					abzielen, einen besonderen, tieferen Sinn, der sich hinter der nur scheinbar
					unsinnigen Textoberfläche verbirgt, zu vermitteln, sind etwa die
					folgenden:</LMMLtext>
			</illustration>
			<quotation booktitle="Romeo and Juliet" authorname="William" authorfamily="Shakespeare">
				<LMMLtext>O loving hate!</LMMLtext>
			</quotation>
			<illustration>
				<LMMLtext>Hier liegt eine <formatted style="hervorhebung">contradictio in
						adiecto</formatted> vor, weil ein Substantiv mit einem diesem (scheinbar)
					widersprechenden Attribut verknüpft wird. Im folgenden Beispiel werden die
					beiden einander widersprechenden Worte sogar zu einem einzigen
					verbunden:</LMMLtext>
			</illustration>
			<quotation booktitle="Heidelberg" authorname="Friedrich" authorfamily="Hölderlin">
				<LMMLtext>[...] traurigfroh [...]</LMMLtext>
			</quotation>
			<illustration>
				<LMMLtext>Aber natürlich können Oxymora auch offensichtlicher – und durchaus so
					gemeinter, weil komischer – Unsinn sein, wie das folgende Liedchen belegt, das
					in verschiedenen Varianten mindestens seit dem 19. Jahrhundert nachweisbar ist:
				</LMMLtext>
			</illustration>
			<illustration>
				<LMMLtext><poem>
						<poemlinegroup>
							<poemline>Finster war’s, der Mond schien helle</poemline>
							<poemline>Auf die grünbeschneite Flur,</poemline>
							<poemline>Als ein Wagen blitzesschnelle</poemline>
							<poemline>Langsam um die Ecke fuhr.</poemline>
							<poemline>Drinnen saßen stehend Leute</poemline>
							<poemline>Schweigend ins Gespräch vertieft,</poemline>
							<poemline>Als ein totgeschossner Hase</poemline>
							<poemline>Auf dem Wasser Schlittschuh lief</poemline>
							<poemline>Und ein blondgelockter Knabe</poemline>
							<poemline>Mit kohlrabenschwarzem Haar</poemline>
							<poemline>Auf die grüne Bank sich setzte,</poemline>
							<poemline>Die gelb angestrichen war.</poemline>
						</poemlinegroup>
					</poem></LMMLtext>
			</illustration>
		</section>
	</section>
</lmml>

=== LG-Online/LiGo/xml_daten/wissensbereiche/rhetorik/alliteration.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"><section type="course" title="Alliteration" author="Uwe Spörl" creationTime="08.04.2007" label="alliteration" topics="Alliteration"><definition title="Alliteration" label="alliterationdef"><LMMLtext>Klangfigur: gleicher Anlaut aufeinanderfolgender Wörter </LMMLtext></definition><illustration><LMMLtext>Die Alliteration ist eine Klangfigur, bei der die Anlaute (und damit in der Regel auch die Anfangsbuchstaben) zweier oder mehrerer aufeinanderfolgender Wörter übereinstimmen.</LMMLtext><LMMLtext>Die antike rhetorische Tradition nennt diese Klangfigur <formatted style="hervorhebung">Homoioprophoron</formatted> (griech. etwa: das, was das Gleiche vor sich her trägt).</LMMLtext><LMMLtext>Die Alliteration kann die Zusammengehörigkeit miteinander verknüpfter Ausdrücke unterstreichen. Sie bewirkt aber insbesondere eine größere Einprägsamkeit, weshalb sie häufig in Werbetexten (z. B. „Spiel, Spaß und Spannung“ oder „Mars macht mobil“) und in pointierten Wendungen (z. B. „Land und Leute“ oder „veni vidi vici“) – auch in poetischen/literarischen Texten („Röslein, Röslein, Röslein rot“) – verwendet wird. Zudem strukturiert die Alliteration als Klangfigur den Text auf der phonologischen und musikalischen Ebene.</LMMLtext></illustration></section></lmml>

=== LG-Online/LiGo/xml_daten/wissensbereiche/drama/song.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"><section type="course" title="Song" author="Martin Huber, Elisabeth Böhm" creationTime="09.09.2007" label="song" topics="Song"><definition title="Song" label="songdef"><LMMLtext>besondere Form des Liedes, im dramatischen Kontext von Brecht für das epische Theater funktionalisiert.</LMMLtext></definition><illustration><LMMLtext>Obwohl schon in den 1920er Jahren im Kabarett der Ausdruck Song für bestimmte Gesangsnummern verwendet wird, die sich an anglo-amerikanische Vorbilder halten und sich bewusst vom Kunstlied distanzieren, prägt besonders Brecht diesen Begriff, indem er ihn in seinen theoretischen Schriften verwendet. Er nennt die Gesangsnummern so, die in seinen Stücken eingesetzt werden. Dabei dienen sie vor allem der <referencesLink target="veffekt"><referencesLink show="new" type="defines" target="veffektdef">Verfremdung</referencesLink></referencesLink>, indem sie durch Form und Präsentation aus dem üblichen Handlungsschema herausfallen und außerdem oft deutlich politische Inhalte transportieren. Mit Komponisten wie Kurt Weill und Hanns Eisler zusammen gestaltet Brecht Lieder, die im Drama aber auch jenseits des handlungsspezifischen Kontexts rezipiert wurden.</LMMLtext></illustration></section></lmml>
