=== LG-Online/LiGo/data/resources/dtd/LMML-CS.dtd
<!ELEMENT LMMLcode (listing?)>
<!ATTLIST LMMLcode
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT LMMLtext (#PCDATA | emphasized | option | poem | quoted | annotated | defined | formatted | math | code | LMMLcode | referencesLink | citesLink | externalLink)*>
<!ATTLIST LMMLtext
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT algorithm ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST algorithm
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT animation EMPTY>
<!ATTLIST animation
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT annotated (#PCDATA | LMMLtext)*>
<!ATTLIST annotated
	label ID #IMPLIED
>
<!ELEMENT bibItem (LMMLtext)>
<!ATTLIST bibItem
	bibKey ID #REQUIRED
>
<!ELEMENT bibliography (bibItem)*>
<!ATTLIST bibliography
	label ID #IMPLIED
	author CDATA #IMPLIED
	authorFirstName CDATA #IMPLIED
	bookYear CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT block (block | line)*>
<!ATTLIST block
	label ID #IMPLIED
>
<!ELEMENT citesLink EMPTY>
<!ATTLIST citesLink
	bibKey NMTOKEN #REQUIRED
	bib-module NMTOKEN #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT collection ((section | collection | glossary | bibliography | motivation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | formula)*)*>
<!ATTLIST collection
	strategy (beh | con) #IMPLIED
	type (course | exercise | coaching | example) #IMPLIED
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT conclusion ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST conclusion
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT defined (#PCDATA)>
<!ATTLIST defined
	label ID #IMPLIED
>
<!ELEMENT definition ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST definition
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT dummycmodel (#PCDATA)>
<!ELEMENT dummylist EMPTY>
<!ELEMENT dummytable EMPTY>
<!ELEMENT emphasized (#PCDATA)>
<!ATTLIST emphasized
	label ID #IMPLIED
>
<!ELEMENT example ((text | image | animation | sound | LMMLtext | table | olist | ulist | quotation | math | code | LMMLcode)*)*>
<!ATTLIST example
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT exercise (text | image | animation | sound | LMMLtext | table | olist | ulist | quotation | math | code | LMMLcode | (task, solution?))*>
<!ATTLIST exercise
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	type CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT externalLink (#PCDATA | emphasized | quoted | annotated | defined | formatted | math | code | LMMLcode)*>
<!ATTLIST externalLink
	uri CDATA #REQUIRED
	exturi CDATA #IMPLIED
	type (illustrates | exercises | defines | remark) #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT formatted (#PCDATA | formatted)*>
<!ATTLIST formatted
	label ID #IMPLIED
	style CDATA #REQUIRED
	title CDATA #IMPLIED
>
<!ELEMENT formula ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST formula
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT glossary (definition)*>
<!ATTLIST glossary
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT illustration ((text | image | poem | animation | sound | LMMLtext | table | olist | ulist | math | code | quotation | LMMLcode)*)*>
<!ATTLIST illustration
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT image EMPTY>
<!ATTLIST image
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT item (text | image | animation | sound | LMMLtext | table | olist | ulist)*>
<!ATTLIST item
	label ID #IMPLIED
>
<!ELEMENT line (#PCDATA | line)*>
<!ATTLIST line
	label ID #IMPLIED
>
<!ELEMENT listing (#PCDATA | block)*>
<!ATTLIST listing
	label ID #IMPLIED
>
<!ELEMENT lmml (section | collection | glossary | bibliography | motivation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | formula)>
<!ATTLIST lmml
	version CDATA #FIXED "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"
>
<!ELEMENT math (#PCDATA)>
<!ATTLIST math
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT motivation ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST motivation
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT olist (item)+>
<!ATTLIST olist
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT option (#PCDATA)*>
<!ATTLIST option
	label ID #IMPLIED
	target CDATA #IMPLIED
>
<!ELEMENT paragraph ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST paragraph
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT poem (poemlinegroup)*>
<!ATTLIST poem
	label ID #IMPLIED
	title CDATA #IMPLIED
	authorname CDATA #IMPLIED
	authorfamily CDATA #IMPLIED
	booktitle CDATA #IMPLIED
>
<!ELEMENT poemlinegroup (poemline)*>
<!ATTLIST poemlinegroup
	label ID #IMPLIED
>
<!ELEMENT poemline (#PCDATA | formatted)*>
<!ATTLIST poemline
	label ID #IMPLIED
>
<!ELEMENT proof ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST proof
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT proposition ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST proposition
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT quotation ((LMMLtext)*)*>
<!ATTLIST quotation
	label ID #IMPLIED
	title CDATA #IMPLIED
	authorname CDATA #IMPLIED
	authorfamily CDATA #IMPLIED
	booktitle CDATA #IMPLIED
	type (example | exercise | luecken) #IMPLIED
>
<!ELEMENT quoted (#PCDATA)>
<!ATTLIST quoted
	label ID #IMPLIED
	bib-module CDATA #IMPLIED
	bibKey NMTOKEN #IMPLIED
>
<!ELEMENT referencesLink (#PCDATA | emphasized | quoted | annotated | defined | formatted | math | code | LMMLcode | referencesLink)*>
<!ATTLIST referencesLink
	target NMTOKEN #REQUIRED
	target-module NMTOKEN #IMPLIED
	type (illustrates | exercises | defines | person | book | test ) #IMPLIED
	show (new | replace | embed) "replace"
>
<!ELEMENT remark ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST remark
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
	audience (students | teachers) #IMPLIED
>
<!ELEMENT section ((section | poem | collection | glossary | bibliography | motivation | animation | conclusion | definition | paragraph | remark | example | exercise | illustration | proposition | theorem | proof | algorithm | quotation | formula)*)*>
<!ATTLIST section
	strategy (beh | con) #IMPLIED
	type (course | exercise | coaching | example | oberbegriff| unterbegriff) #IMPLIED
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT solution ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST solution
	label ID #IMPLIED
	true (true | false) #IMPLIED
>
<!ELEMENT sound EMPTY>
<!ATTLIST sound
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT table (tableheading?, tablerow+)>
<!ATTLIST table
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT tabledata (text | image | animation | sound | LMMLtext | table | olist | ulist)*>
<!ELEMENT tableheading (tabledata+)>
<!ELEMENT tablerow (tabledata+)>
<!ELEMENT task ((text | image | animation | sound | externalLink | LMMLtext | table | olist | ulist | math | code | quotation | LMMLcode)*)*>
<!ATTLIST task
	type CDATA #IMPLIED
	target CDATA #IMPLIED
>
<!ELEMENT text EMPTY>
<!ATTLIST text
	type CDATA #IMPLIED
	title CDATA #IMPLIED
	label ID #IMPLIED
	uri CDATA #IMPLIED
	style CDATA #IMPLIED
>
<!ELEMENT theorem ((text | image | animation | sound | LMMLtext | table | olist | ulist | math | code | LMMLcode)*)*>
<!ATTLIST theorem
	label ID #IMPLIED
	author CDATA #IMPLIED
	title CDATA #IMPLIED
	creationTime CDATA #IMPLIED
	modifiedTime CDATA #IMPLIED
	releaseTime CDATA #IMPLIED
	expirationTime CDATA #IMPLIED
	language NMTOKEN #IMPLIED
	topics CDATA #IMPLIED
	discipline CDATA #IMPLIED
	difficulty (low | medium | high) #IMPLIED
	theoretical (true | false) #IMPLIED
	related2practice (true | false) #IMPLIED
	formality (low | medium | high) #IMPLIED
	abstraction (low | medium | high) #IMPLIED
	density (low | medium | high) #IMPLIED
	uri CDATA #IMPLIED
	viewspec CDATA #IMPLIED
>
<!ELEMENT ulist (item)+>
<!ATTLIST ulist
	title CDATA #IMPLIED
	label ID #IMPLIED
	style CDATA #IMPLIED
>

=== LG-Online/LiGo/xml_daten/wissensbereiche/drama/historischeanforderungen.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"><section type="course" title="Historische Anforderungen" author="Martin Huber, Elisabeth Böhm" creationTime="09.09.2007" label="historischeanforderungen" topics="Historische Anforderungen"><illustration><LMMLtext>In der Geschichte des Dramas wurden immer wieder verschiedene Anforderungen an dessen Entwicklung gestellt. Denn je nach der Funktion, die das Theater in einem bestimmten Kontext einzunehmen hatte, musste es formalen und inhaltlichen Ansprüchen genügen. <referencesLink target="staendeklausel"><referencesLink show="new" type="defines" target="staendeklauseldef">Ständeklausel</referencesLink></referencesLink> und <referencesLink target="fallhoehe"><referencesLink show="new" type="defines" target="fallhoehedef">Fallhöhe</referencesLink></referencesLink> können als Beispiele gut illustrieren, wie sich bestimmte Vorstellungen von Gesellschaft und Personalität in der Theaterästhetik niederschlagen.</LMMLtext></illustration></section></lmml>

=== LG-Online/LiGo/xml_daten/wissensbereiche/prosa/indirektegedankenrede.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"><section type="course" title="Indirekte Gedankenrede" author="Fotis Jannidis, Uwe Spörl, Katrin Fischer" creationTime="30.07.2005" label="indirektegedankenrede" modifiedTime="27.10.07"><definition title="Indirekte Gedankenrede" label="indirektegedankenrededef"><LMMLtext>Erzählerische Gedankenwiedergabe in der 3. Person Präsens Konjunktiv (bei Ich-Erzählung: in der 1. Person für das erlebende Ich), mit der Möglichkeit kommentierender Einmischung, in vollständiger Syntax ohne Anführungs-, Ausrufe- und Fragezeichen.</LMMLtext><LMMLtext>In indirekter Gedankenrede bleibt zwar der Inhalt der Gedanken der Figur erhalten, nicht 
jedoch ihr Wortlaut, da das Gesagte einem anderen Sprecher, dem Erzähler, als Inhalt eines „dass“-Satzes im Konjunktiv zugeordnet wird.</LMMLtext></definition><illustration><LMMLtext><referencesLink type="illustrates" target="beispielindirektegedankenredeBsp"></referencesLink><referencesLink type="exercises" target="uebungzurindirektengedankenredeUeb"></referencesLink></LMMLtext></illustration><section type="example" title="Beispiel indirekte Gedankenrede" label="beispielindirektegedankenredeBsp"><quotation booktitle="Die Wahlverwandtschaften (16. Kapitel)" authorname="Jahann Wolfgang" authorfamily="von Goethe"><LMMLtext>Er faßte sich; er dachte, <formatted style="hervorhebung">daß</formatted> es ihm doch möglich <formatted style="hervorhebung">sei</formatted>, jeden Augenblick zurückzukehren und durch die Entfernung gerade seinen Wünschen näher zu kommen.</LMMLtext></quotation><illustration label="beispielindirektegedankenredeBspIllu"><LMMLtext>Die Konjunktion „daß“ in Verbindung mit dem Konjunktiv lässt deutlich erkennen, dass die Gedanken nicht wörtlich wiedergegeben werden, sondern in die <referencesLink show="new" type="defines" target="indirektegedankenrededef">indirekte Gedankenrede</referencesLink> transponiert sind.</LMMLtext></illustration></section><exercise label="uebungzurindirektengedankenredeUeb" title="Übung zur indirekten Gedankenrede" topics="multiplechoice"><task type="textbeispiel"><quotation booktitle="Wilhelm Meisters Lehrjahre (11. Kapitel)" authorname="Johann Wolfgang" authorfamily="von Goethe"><LMMLtext>So groß war seine Leidenschaft, so rein seine Überzeugung, er handle vollkommen recht, sich dem Drucke seines bisherigen Lebens zu entziehen und einer neuen, edlern Bahn zu folgen, daß sein Gewissen sich nicht im mindesten regte, keine Sorge in ihm entstand, ja daß er vielmehr diesen Betrug für heilig hielt. Er war gewiß, daß ihn Eltern und Verwandte in der Folge für diesen Schritt preisen und segnen sollten, er erkannte den Wink eines leitenden Schicksals an diesen zusammentreffenden Umständen.</LMMLtext></quotation></task><task type="fragestellung"><LMMLtext> Hat man es hier mit<referencesLink show="new" type="defines" target="indirektegedankenrededef"> indirekter Gedankenrede</referencesLink>, mit <referencesLink show="new" type="defines" target="erlebtegedankenrededef">erlebter Gedankenrede</referencesLink> oder einem <referencesLink show="new" type="defines" target="bewusstseinsberichtdef">Bewusstseinsbericht</referencesLink> zu tun?</LMMLtext></task><task type="alternative" target="uebungzurindirektengedankenredeL1"><LMMLtext>Mit <referencesLink show="new" type="defines" target="indirektegedankenrededef">indirekter Gedankenrede</referencesLink>, erkennbar am wiederholten Auftreten der Konjunktion „dass“.</LMMLtext></task><solution label="uebungzurindirektengedankenredeL1" true="false"><LMMLtext> Die Konjunktion „dass“ folgt hier nicht auf einleitende Verben des Sagens und Meinens und zieht auch nur in einem Fall den Konjunktiv. Sie indiziert somit keine <referencesLink show="new" type="defines" target="indirektegedankenrededef">indirekte Gedankenrede</referencesLink>.</LMMLtext></solution><task type="alternative" target="uebungzurindirektengedankenredeL2"><LMMLtext> Hier liegt eindeutig <referencesLink show="new" type="defines" target="erlebtegedankenrededef">erlebte Gedankenrede</referencesLink> vor, weil man das Gefühl hat, die Gedanken der Figur selbst zu erleben.</LMMLtext></task><solution label="uebungzurindirektengedankenredeL2" true="false"><LMMLtext>Mit der Partizipation an den Bewusstseinsvorgängen von Figuren hat der Begriff <referencesLink show="new" type="defines" target="erlebtegedankenrededef">erlebte Gedankenrede</referencesLink> nur sehr bedingt etwas zu tun. Wir haben es hier zwar mit einer Gedankenwiedergabe in der 3. Person Präteritum Indikativ mit Innensicht zu tun, haben aber zusätzlich Verben des Fühlens („dass sich sein Gewissen regte“, „für heilig hielt“ „Er war gewiß“), die auf die Vermitteltheit der Gedankenwiedergabe aufmerksam machen.</LMMLtext></solution><task type="alternative" target="uebungzurindirektengedankenredeL3"><LMMLtext>Die ganze Passage ist ein <referencesLink show="new" type="defines" target="bewusstseinsberichtdef">Bewusstseinsbericht</referencesLink>.</LMMLtext></task><solution label="uebungzurindirektengedankenredeL3" true="true"><LMMLtext>Bestimmte Verben und Formulierungen („dass sich sein Gewissen regte“, „für heilig hielt“ „Er war gewiß“) weisen den Leser darauf hin, dass wir es hier  mit einem Erzähler zu tun haben, der uns die Gedanken einer Figur berichtet.</LMMLtext></solution></exercise></section></lmml>

=== LG-Online/LiGo/data/xml_wissensbereiche/drama/fallhoehe.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../stylesheets/layout.xsl" type="text/xsl"?>
<!DOCTYPE lmml PUBLIC "-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN" "../../resources/dtd//LMML-CS.dtd">
<lmml version="-//DE.UNI-PASSAU.IM//DTD LMML-CS 1.1//EN"><section type="course" title="Fallhöhe" author="Martin Huber, Elisabeth Böhm" creationTime="09.09.2007" label="fallhoehe" topics="Fallhöhe"><definition title="Fallhöhe" label="fallhoehedef"><LMMLtext>Kategorie der Dramentheorie, die besagt, dass der Fall eines Helden umso eindringlicher empfunden wird, je höher sein sozialer und moralischer Rang vorher war.</LMMLtext></definition><illustration><LMMLtext>Die Fallhöhe ist eng mit der Ständeklausel verknüpft und markiert nochmals den Zusammenhang von moralischem und sozialem Stand nach klassizistischem Verständnis. Nur der Fall eines hochstehenden, moralisch gefestigten Helden könne die gewünscht Wirkung beim Publikum erzielen, heißt es bei Aristoteles. Allerdings findet sich dort auch die Forderung nach einem Fehler des Helden, so dass dessen Fall nicht gänzlich unmotiviert und unverdient erscheint. Jedoch ist es die Tiefe des Sturzes sowie das Verhalten des Untergehenden, die eine entsprechende Publikumswirkung vermitteln können. Der Zusammenhang von sprachlichem Stil, gezeigter Gesinnung und Schwere des Konflikts darf auch hier nicht unbeachtet bleiben. </LMMLtext><LMMLtext>Mit zunehmender Modernisierung des Dramenverständnisses und Wegfall der Ständeklausel verliert auch die Fallhöhe ihre Bedeutung, da auch Figuren niederen Stands in Konflikten gezeigt werden bzw. die Probleme der Reichen und des Adels kaum noch von denen der Bürger unterschieden werden können (vgl. Schnitzler).</LMMLtext><LMMLtext><referencesLink type="illustrates" target="beispielfallhoeheBsp"></referencesLink></LMMLtext><LMMLtext>Inhaltlich und stilistisch lassen sich diese Anforderungen in <referencesLink target="hamartia"><referencesLink show="new" type="defines" target="hamartiadef">Hamartia</referencesLink></referencesLink>, <referencesLink target="intrige"><referencesLink show="new" type="defines" target="intrigedef">Intrige</referencesLink></referencesLink> und <referencesLink target="pathos"><referencesLink show="new" type="defines" target="pathosdef">Pathos</referencesLink></referencesLink> finden, die sich zwar auch historisch veränderten, aber bis ins 19. Jahrhundert zentrale Positionen in den Dramen und ihrer theoretischen Reflexion einnahmen.</LMMLtext></illustration><section type="example" title="Beispiel Fallhöhe" label="beispielfallhoeheBsp"><quotation><LMMLtext>I Sophokles: König Ödipus</LMMLtext><LMMLtext type="br">Personen:</LMMLtext><LMMLtext type="br">ÖDIPUS, König von Theben</LMMLtext><LMMLtext type="br">PRIESTER des Zeus</LMMLtext><LMMLtext type="br">KREON, Bruder der Königin</LMMLtext><LMMLtext type="br">TEIRESIAS, ein blinder Seher</LMMLtext><LMMLtext type="br">IOKASTE, Königin</LMMLtext><LMMLtext type="br">BOTE aus Korinth</LMMLtext><LMMLtext type="br">HIRTE des Laios</LMMLtext><LMMLtext type="br">DIENER</LMMLtext></quotation><quotation><LMMLtext>II Gotthold Ephraim Lessing: Emilia Galotti</LMMLtext><LMMLtext type="br">Personen:</LMMLtext><LMMLtext type="br">EMILIA GALOTTI</LMMLtext><LMMLtext type="br">ODOARDO und CLAUDIA GALOTTI, Eltern der Emilia</LMMLtext><LMMLtext type="br">HETTORE GONZAGA, Prinz von Guastalla</LMMLtext><LMMLtext type="br">MARINELLI, Kammerherr des Prinzen</LMMLtext><LMMLtext type="br">CAMILLO ROTA, einer von des Prinzen Räten</LMMLtext><LMMLtext type="br">CONTI, Maler</LMMLtext><LMMLtext type="br">Graf APPIANI</LMMLtext><LMMLtext type="br">Gräfin ORSINA</LMMLtext><LMMLtext type="br">ANGELO und einige Bediente</LMMLtext></quotation><quotation><LMMLtext>III Schnitzler: Liebelei</LMMLtext><LMMLtext type="br">Personen:</LMMLtext><LMMLtext type="br">HANS WEIRING, Violinspieler am Josefstädter Theater</LMMLtext><LMMLtext type="br">CHRISTINE, seine Tochter</LMMLtext><LMMLtext type="br">MIZI SCHLAGER, Modistin</LMMLtext><LMMLtext type="br">KATHARINA BINDER, Frau eines Strumpfwirkers</LMMLtext><LMMLtext type="br">LINA, ihre Tochter</LMMLtext><LMMLtext type="br">FRITZ LOBHEIMER und THEODOR KRAUSE, junge Leute</LMMLtext><LMMLtext type="br">EIN HERR</LMMLtext></quotation>
						</section></section></lmml>
